SNAIL01_V100_FLAGS = \
	--host snail01:2 \
	-x CUDA_VISIBLE_DEVICES=2,3 \
	-x NCCL_IB_HCA=mlx5_0,mlx5_1
SNAIL02_V100_FLAGS = \
	--host snail02:2 \
	-x CUDA_VISIBLE_DEVICES=0,1 \
	-x NCCL_IB_HCA=mlx5_1,mlx5_2
SNAIL03_V100_FLAGS = \
	--host snail03:2 \
	-x CUDA_VISIBLE_DEVICES=0,1 \
	-x NCCL_IB_HCA=mlx5_1,mlx5_2
TVM01_V100_FLAGS = \
	--host tvm01:2 \
	-x CUDA_VISIBLE_DEVICES=0,1 \
	-x NCCL_IB_HCA=mlx5_1,mlx5_2
TVM02_V100_FLAGS = \
	--host tvm02:2 \
	-x CUDA_VISIBLE_DEVICES=0,1 \
	-x NCCL_IB_HCA=mlx5_1,mlx5_2
SNAIL99_V100_FLAGS = \
	--host snail99:2 \
	-x CUDA_VISIBLE_DEVICES=0,1 \
	-x NCCL_IB_HCA=mlx5_1,mlx5_2


SNAIL01_V100_3_FLAGS = \
	--host snail01:1 \
	-x CUDA_VISIBLE_DEVICES=3 \
	-x NCCL_IB_HCA=mlx5_1
SNAIL01_V100_2_FLAGS = \
	--host snail01:1 \
	-x CUDA_VISIBLE_DEVICES=2 \
	-x NCCL_IB_HCA=mlx5_0
SNAIL01_V100_3_FLAGS = \
	--host snail01:1 \
	-x CUDA_VISIBLE_DEVICES=3 \
	-x NCCL_IB_HCA=mlx5_1
SNAIL02_V100_0_FLAGS = \
	--host snail02:1 \
	-x CUDA_VISIBLE_DEVICES=0 \
	-x NCCL_IB_HCA=mlx5_1
SNAIL02_V100_1_FLAGS = \
	--host snail02:1 \
	-x CUDA_VISIBLE_DEVICES=1 \
	-x NCCL_IB_HCA=mlx5_2

FLAGS = \
	--mca plm_rsh_args "-p 2222" \
	-x NCCL_DEBUG=TRACE

run:
	mpirun \
	  -n 2 $(SNAIL01_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf \
	: -n 2 $(SNAIL02_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf \
	: -n 2 $(SNAIL03_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf \
	: -n 2 $(TVM01_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf \
	: -n 2 $(TVM02_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf


run_tvm01:
	mpirun \
	  -n 2 $(SNAIL01_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf \
	: -n 2 $(TVM01_V100_FLAGS) $(FLAGS) 3rd-party/nccl-tests/build/reduce_perf


